export const PINECONE_CATEGORIES = [
  "ADDICTION",
  "MIND",
  "BODY",
  "SEXUALITY",
  "TRANSITIONS",
  "SPIRITUALITY",
  "SCIENCE",
  "PSYCHEDELICS",
  "NUTRITION",
  "LIFE",
  "LONGEVITY",
  "GRIEF",
  "MIDLIFE",
  "MOVEMENT",
  "WORK",
  "SLEEP",
  "MEDICAL",
  "HEALTH",
  "WELLNESS",
  "HEALING",
  "BUSINESS",
  "LEADERSHIP",
  "CAREER",
  "ANN",
  "DEXTER",
  "JUDY",
  "JUNE",
  "KELSEY",
  "MARK_KOHL",
  "NIGEL",
  "SHAWN",
  "THAD",
  "WILLIE_GAULT",
  "OTHER"
] as const;

export type PineconeCategory = typeof PINECONE_CATEGORIES[number];

export const CATEGORY_DESCRIPTIONS: Record<PineconeCategory, string> = {
  ADDICTION: "Addiction, recovery, and substance-related topics",
  MIND: "Mental health, psychology, and cognitive wellness",
  BODY: "Physical health, anatomy, and body wellness",
  SEXUALITY: "Sexual health, intimacy, and relationships",
  TRANSITIONS: "Life transitions, change, and adaptation",
  SPIRITUALITY: "Spiritual practices, consciousness, and meaning",
  SCIENCE: "Scientific research, studies, and evidence-based knowledge",
  PSYCHEDELICS: "Psychedelic compounds, research, and therapeutic use",
  NUTRITION: "Diet, nutrition, and food-related wellness",
  LIFE: "General life guidance, purpose, and fulfillment",
  LONGEVITY: "Aging, lifespan, and healthspan optimization",
  GRIEF: "Loss, bereavement, and emotional processing",
  MIDLIFE: "Midlife transitions, challenges, and opportunities",
  MOVEMENT: "Exercise, fitness, and physical movement",
  WORK: "Career, professional development, and work-life balance",
  SLEEP: "Sleep health, optimization, and rest",
  MEDICAL: "Medical conditions, treatments, and clinical topics",
  HEALTH: "General health topics, wellness practices, and preventive care",
  WELLNESS: "Holistic wellness, self-care, and well-being practices",
  HEALING: "Healing modalities, recovery processes, and therapeutic approaches",
  BUSINESS: "Business strategy, entrepreneurship, and organizational topics",
  LEADERSHIP: "Leadership development, management, and team building",
  CAREER: "Career development, job skills, and professional growth",
  ANN: "Ann's personal knowledge, experiences, and expertise",
  DEXTER: "Dexter's personal knowledge, experiences, and expertise",
  JUDY: "Judy's personal knowledge, experiences, and expertise",
  JUNE: "June's personal knowledge, experiences, and expertise",
  KELSEY: "Kelsey's personal knowledge, experiences, and expertise",
  MARK_KOHL: "Mark Kohl's personal knowledge, experiences, and expertise",
  NIGEL: "Nigel's personal knowledge, experiences, and expertise",
  SHAWN: "Shawn's personal knowledge, experiences, and expertise",
  THAD: "Thad's personal knowledge, experiences, and expertise",
  WILLIE_GAULT: "Willie Gault's personal knowledge, experiences, and expertise",
  OTHER: "Miscellaneous topics not fitting other categories"
};
